version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=dockercma
      - POSTGRES_PASSWORD=dockercma
      - POSTGRES_DB=cma
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data: